name: npm package publish

on:
  # release:
  #   types: [created]
  push:
    branches:
      - 'main'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      # - uses: actions/checkout@v4
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 20
      #     registry-url: https://npm.pkg.github.com/
      # - run: npm ci
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2

      - name: Setup Node and pnpm-store cache
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Dump versions
        run: |
          echo "node: $(node -v)"
          echo "npm: $(npm -v)"
          echo "pnpm: $(pnpm -v)"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup script cache
        uses: actions/cache@v3
        with:
          path: node_modules/.cache
          key: script-cache-${{ hashFiles('**/pnpm-lock.yaml') }}-run-id-${{ github.run_id }}
          restore-keys: script-cache-${{ hashFiles('**/pnpm-lock.yaml') }}-run-id-

      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
